In [10]:
from sudoku_c import solve
# print(f"sudoku_c{__version__}")
import numpy as np
import time

ImportError: cannot import name 'solve' from 'sudoku_c' (unknown location)

In [8]:
filepath = '../data/evil_2.csv'
x = np.loadtxt(filepath, delimiter=',').astype(np.uint16)
print(x)

[[0 0 4 0 5 0 0 0 1]
 [0 0 6 0 0 0 0 3 0]
 [5 3 0 7 0 0 0 0 8]
 [1 2 0 0 6 0 0 8 0]
 [0 0 3 0 0 0 0 0 0]
 [0 0 0 0 0 9 0 0 7]
 [4 0 0 0 0 0 0 0 0]
 [8 5 0 0 1 0 0 2 0]
 [0 0 0 6 0 0 1 0 0]]


In [9]:
start = time.perf_counter()
y = solve(x)
end = time.perf_counter()
elapsed = end - start
print(y)
print(f'elapsed time: {elapsed:.6f}')

[[2 6 4 3 5 7 8 9 1]
 [7 1 6 2 4 8 5 3 9]
 [5 3 1 7 2 4 9 6 8]
 [1 2 7 9 6 3 4 8 5]
 [6 8 3 5 9 1 2 7 4]
 [3 4 2 1 8 9 6 5 7]
 [4 9 5 8 7 2 3 1 6]
 [8 5 9 4 1 6 7 2 3]
 [9 7 8 6 3 5 1 4 2]]
elapsed time: 0.002027
